const acbDrinkData = {
  'drinks': [
    { 
      'dateModified': '2016-08-31 19:32:08',
      'idDrink': '13501',
      'strAlcoholic': 'Alcoholic',
      'strCategory': 'Shot',
      'strCreativeCommonsConfirmed': 'No',
      'strDrink': 'ABC',
      'strDrinkAlternate': null,
      'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/tqpvqp1472668328.jpg',
      'strGlass': 'Shot glass',
      'strIBA': null,
      'strImageAttribution': null,
      'strImageSource': null,
      'strIngredient1': 'Amaretto',
      'strIngredient2': 'Baileys irish cream',
      'strIngredient3': 'Cognac',
      'strIngredient4': null,
      'strIngredient5': null,
      'strIngredient6': null,
      'strIngredient7': null,
      'strIngredient8': null,
      'strIngredient9': null,
      'strIngredient10': null,
      'strIngredient11': null,
      'strIngredient12': null,
      'strIngredient13': null,
      'strIngredient14': null,
      'strIngredient15': null,
      'strInstructions': 'Layered in a shot glass.',
      'strInstructionsDE': 'Schichtaufbau in einem Schnapsglas.',
      'strInstructionsES': 'Coloque todos los ingredientes en un vaso de chupito.',
      'strInstructionsFR': null,
      'strInstructionsIT': `Versa in ordine di lettera i vari ingredienti. 
          1/3 del bicchiere va riempito con l'Amaretto, 1/3 
          di Baileys e il restante di Cognac.`,
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      'strMeasure1': '1/3 ',
      'strMeasure2': '1/3 ',
      'strMeasure3': '1/3 ',
      'strMeasure4': null,
      'strMeasure5': null,
      'strMeasure6': null,
      'strMeasure7': null,
      'strMeasure8': null,
      'strMeasure9': null,
      'strMeasure10': null,
      'strMeasure11': null,
      'strMeasure12': null,
      'strMeasure13': null,
      'strMeasure14': null,
      'strMeasure15': null,
      'strTags': null,
      'strVideo': null,
    }
  ],
};

module.exports = acbDrinkData;
