const poutineData = {
  meals: [
    {
      dateModified: null,
      idMeal: '52804',
      strArea: 'Canadian',
      strCategory: 'Miscellaneous',
      strCreativeCommonsConfirmed: null,
      strDrinkAlternate: null,
      strImageSource: null,
      strIngredient1: 'Vegetable Oil',
      strIngredient2: 'Beef Gravy',
      strIngredient3: 'Potatoes',
      strIngredient4: 'Cheese Curds',
      strIngredient5: '',
      strIngredient6: '',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strInstructions: `Heat oil in a deep fryer or deep heavy skillet to 365°F (185°C)
  .\r\nWarm gravy in saucepan or microwave.\r\nPlace the fries into the hot oil,
   and cook until light brown, about 5 minutes.\r\nRemove to a paper towel lined plate 
   to drain.\r\nPlace the fries on a serving platter, and sprinkle the cheese over them
  .\r\nLadle gravy over the fries and cheese, and serve immediately.`,
      strMeal: 'Poutine',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuyrrx1487327597.jpg',
      strMeasure1: 'Dash',
      strMeasure2: '1 Can',
      strMeasure3: '5 thin cut',
      strMeasure4: '2 cups',
      strMeasure5: '',
      strMeasure6: '',
      strMeasure7: '',
      strMeasure8: '',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://www.food.com/recipe/real-canadian-poutine-113388',
      strTags: 'UnHealthy,Speciality,HangoverFood',
      strYoutube: 'https://www.youtube.com/watch?v=UVAMAoA2_WU',
    }],
};

module.exports = poutineData;
